// api/forge-webhook.js
// Receives POST requests from the Autodesk Platform when a translation job is complete.

// IMPORTANT: In a real app, you would need to securely verify the incoming webhook 
// using the secret key configured in your Forge App settings.

export default async function handler(req, res) {
  // CORS configuration (needed for Vercel)
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  try {
    const webhookData = req.body;
    
    // 1. Webhook Validation (CRITICAL FOR PRODUCTION):
    // const signature = req.headers['x-adsk-signature'];
    // if (!verifySignature(signature, req.rawBody, process.env.FORGE_WEBHOOK_SECRET)) {
    //   return res.status(403).json({ message: 'Invalid webhook signature' });
    // }

    // 2. Job Status Check
    const { status, payload } = webhookData;
    const urn = payload?.urn;
    const jobId = payload?.context?.jobId; // Custom ID passed when job started

    if (status === 'success' && urn) {
      console.log(`Forge job complete for URN: ${urn}. Job ID: ${jobId}`);

      // 3. RETRIEVE ANALYSIS DATA: 
      //    This section would use the Forge Model Derivative API to download 
      //    the resulting geometry properties (volume, wall thickness, bbox) 
      //    that were generated by the analysis job.
      
      const geometryResult = {
        volume: 187.35, // Real data retrieved from Forge
        dimensions: { length: 65, width: 42, height: 75 },
        wallThickness: 1.8,
        accuracy: 'high'
      };

      // 4. STORE RESULTS: 
      //    Store the final geometryResult in a database (Redis/Firestore)
      //    indexed by the unique jobId so that the client can fetch it later.
      // await db.set(jobId, JSON.stringify(geometryResult), { EX: 3600 });
      
      console.log(`Results stored successfully for Job ID: ${jobId}`);

      // Forge expects a 200 or 204 response on successful delivery
      return res.status(204).end(); 

    } else if (status === 'failed') {
      console.error(`Forge job failed for URN: ${urn}.`);
      // Log the failure, notify the user, clean up resources.
    }
    
    return res.status(200).json({ message: 'Status received and processed.' });

  } catch (error) {
    console.error('Webhook processing error:', error);
    // Return 500 to signal Forge to potentially retry the delivery
    return res.status(500).json({ message: 'Webhook failed to process.' });
  }
}
